name: "docs"
navbar:
  title: "Yellow Island 2022"
  right:
    - text: "Schedule & materials"
      href: lectures.html
    - text: "Homework"
      href: homework.html
    - text: "Meet the Team"
      href: team.html
    - text: ""
      icon: fab fa-github
      href: https://github.com/chrismantegna/yellowislandddcsp
output_dir: "docs"
output:
  html_document:
    theme: cerulean
    highlight: textmate
